CREATE TABLE `khachhang` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`ten` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`diaChi` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`soDienThoai` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`goiInternet` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=7
;
CREATE TABLE `taikhoan` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`tenDangNhap` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`matKhau` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `tenDangNhap` (`tenDangNhap`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;

